"use client";
import { useEffect, useRef, useState } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import Link from 'next/link';
import { useUser } from '@clerk/nextjs';
import { useRouter } from 'next/navigation';

export default function LandingPage() {
  const containerRef = useRef(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const { scrollYProgress } = useScroll();
  const opacity = useTransform(scrollYProgress, [0, 0.5], [1, 0]);
  const { user, isLoaded: isUserLoaded } = useUser();
  const router = useRouter();

  useEffect(() => {
    setIsLoaded(true);
  }, []);

  // Redirect authenticated users to dashboard
  useEffect(() => {
    if (isUserLoaded && user) {
      router.push('/dashboard');
    }
  }, [isUserLoaded, user, router]);

  // Don't render the landing page content if user is authenticated
  if (isUserLoaded && user) {
    return null; // This will show a loading state while redirecting
  }

  const features = [
    {
      icon: "🎯",
      title: "AI-Powered Learning",
      description: "Personalized study materials generated by advanced AI technology tailored to your learning style",
      color: "from-blue-500 to-cyan-500"
    },
    {
      icon: "📚",
      title: "Smart Content Creation",
      description: "Generate courses, quizzes, flashcards, and study notes with just a topic description",
      color: "from-purple-500 to-pink-500"
    },
    {
      icon: "📊",
      title: "Progress Analytics",
      description: "Track your learning journey with detailed analytics and performance insights",
      color: "from-green-500 to-emerald-500"
    },
    {
      icon: "🔄",
      title: "Interactive Learning",
      description: "Engage with dynamic quizzes, flashcards, and Q&A sessions for better retention",
      color: "from-orange-500 to-red-500"
    },
    {
      icon: "⚡",
      title: "Quick & Easy",
      description: "Create comprehensive study materials in minutes, not hours",
      color: "from-indigo-500 to-blue-500"
    },
    {
      icon: "🎓",
      title: "Multiple Study Types",
      description: "Choose from quizzes, flashcards, notes, and Q&A formats for diverse learning",
      color: "from-teal-500 to-cyan-500"
    }
  ];

  const testimonials = [
    {
      name: "Sarah Johnson",
      role: "Medical Student",
      content: "Easy Study transformed my exam preparation. The AI-generated flashcards are incredibly accurate and helped me ace my finals!",
      avatar: "👩‍⚕️"
    },
    {
      name: "Michael Chen",
      role: "Software Engineer",
      content: "I use Easy Study for learning new programming concepts. The interactive quizzes make complex topics much easier to understand.",
      avatar: "👨‍💻"
    },
    {
      name: "Emma Rodriguez",
      role: "High School Teacher",
      content: "This platform is a game-changer for my classroom. I can create engaging study materials in minutes for any subject.",
      avatar: "👩‍🏫"
    }
  ];

  return (
    <div ref={containerRef} className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900/30 to-slate-900 text-white overflow-hidden">
      {/* Animated Background */}
      <div className="fixed inset-0 overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_80%,_rgba(0,78,235,0.12)_0%,_transparent_50%)]" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,_rgba(59,130,246,0.08)_0%,_transparent_50%)]" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_40%_40%,_rgba(99,102,241,0.06)_0%,_transparent_50%)]" />
      </div>

      {/* Navigation */}
      <nav className="relative z-50 py-6 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="w-10 h-10 bg-gradient-to-r from-blue-600 to-blue-700 rounded-lg flex items-center justify-center">
              <svg fill="none" height="24" viewBox="0 0 40 48" width="20" xmlns="http://www.w3.org/2000/svg">
                <g fill="white">
                  <path d="m32 26c0 5.5228-4.4772 10-10 10s-10-4.4772-10-10h-8c0 9.9411 8.0589 18 18 18s18-8.0589 18-18-8.0589-18-18-18v8c5.5228 0 10 4.4772 10 10z"/>
                  <path d="m10 4c0 5.52285-4.47715 10-10 10v8c9.94113 0 18-8.0589 18-18z" opacity=".5"/>
                </g>
              </svg>
            </div>
            <span className="text-xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
              Easy Study
            </span>
          </div>
          <div className="hidden md:flex items-center space-x-8">
            <a href="#features" className="text-gray-200 hover:text-white transition-colors font-medium">Features</a>
            <a href="#testimonials" className="text-gray-200 hover:text-white transition-colors font-medium">Testimonials</a>
            <a href="#pricing" className="text-gray-200 hover:text-white transition-colors font-medium">Pricing</a>
          </div>
          <div className="flex items-center space-x-4">
            <Link href="/sign-in" className="text-gray-200 hover:text-white transition-colors font-medium">
              Sign In
            </Link>
            <Link href="/sign-up" className="px-4 py-2 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 rounded-lg font-medium transition-all duration-200 transform hover:scale-105">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <motion.div 
        style={{ opacity }}
        className="relative min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8"
      >
        <div className="container mx-auto text-center z-10">
          <motion.h1 
            className="text-5xl md:text-7xl lg:text-8xl font-bold mb-8"
            initial={{ opacity: 0, y: 50 }}
            animate={isLoaded ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, ease: "easeOut" }}
          >
            <span className="bg-gradient-to-r from-blue-400 via-cyan-400 to-blue-600 bg-clip-text text-transparent">
              Master Any Subject
            </span>
            <br />
            <span className="text-white">with AI-Powered Learning</span>
          </motion.h1>
          
          <motion.p 
            className="text-xl md:text-2xl text-gray-100 mb-12 max-w-4xl mx-auto leading-relaxed font-medium"
            initial={{ opacity: 0, y: 30 }}
            animate={isLoaded ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2, ease: "easeOut" }}
          >
            Transform your learning experience with intelligent study materials, interactive quizzes, 
            and personalized content generated by cutting-edge AI technology.
          </motion.p>
          
          <motion.div 
            className="flex flex-col sm:flex-row justify-center gap-4 mb-16"
            initial={{ opacity: 0, y: 30 }}
            animate={isLoaded ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.4, ease: "easeOut" }}
          >
            <Link 
              href="/dashboard" 
              className="px-8 py-4 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 rounded-xl font-semibold text-lg transition-all duration-200 transform hover:scale-105 shadow-lg hover:shadow-blue-500/25"
            >
              Start Learning Free
            </Link>
            <Link 
              href="#features" 
              className="px-8 py-4 border-2 border-blue-600 hover:bg-blue-600/20 rounded-xl font-semibold text-lg transition-all duration-200 transform hover:scale-105"
            >
              See How It Works
            </Link>
          </motion.div>

          {/* Hero Stats */}
          <motion.div 
            className="grid grid-cols-3 gap-8 max-w-2xl mx-auto"
            initial={{ opacity: 0, y: 30 }}
            animate={isLoaded ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.6, ease: "easeOut" }}
          >
            {[
              { number: "50K+", label: "Students" },
              { number: "100K+", label: "Courses" },
              { number: "98%", label: "Success Rate" }
            ].map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-2xl md:text-3xl font-bold text-blue-300 mb-1">{stat.number}</div>
                <div className="text-gray-200 text-sm font-medium">{stat.label}</div>
              </div>
            ))}
          </motion.div>
        </div>

        {/* Floating Elements */}
        <div className="absolute inset-0 pointer-events-none">
          <motion.div
            animate={{ y: [0, -20, 0] }}
            transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
            className="absolute top-20 left-10 w-4 h-4 bg-blue-500 rounded-full opacity-40"
          />
          <motion.div
            animate={{ y: [0, 20, 0] }}
            transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
            className="absolute top-40 right-20 w-6 h-6 bg-cyan-500 rounded-full opacity-30"
          />
          <motion.div
            animate={{ y: [0, -15, 0] }}
            transition={{ duration: 7, repeat: Infinity, ease: "easeInOut" }}
            className="absolute bottom-40 left-20 w-3 h-3 bg-blue-400 rounded-full opacity-35"
          />
        </div>
      </motion.div>

      {/* Features Section */}
      <section id="features" className="py-20 relative">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Why Choose <span className="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">Easy Study</span>?
            </h2>
            <p className="text-xl text-gray-100 max-w-3xl mx-auto font-medium">
              Our AI-powered platform revolutionizes learning with intelligent content generation and personalized study experiences.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                className="group p-8 rounded-2xl bg-white/8 backdrop-blur-sm border border-white/15 hover:border-blue-500/50 transition-all duration-300 hover:bg-white/12"
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                whileHover={{ scale: 1.02, y: -5 }}
                whileTap={{ scale: 0.98 }}
              >
                <div className={`w-16 h-16 rounded-xl bg-gradient-to-r ${feature.color} flex items-center justify-center text-2xl mb-6 group-hover:scale-110 transition-transform duration-300`}>
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold mb-4 text-white">{feature.title}</h3>
                <p className="text-gray-200 leading-relaxed font-medium">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 bg-gradient-to-r from-blue-900/25 to-cyan-900/25">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              How <span className="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">Easy Study</span> Works
            </h2>
            <p className="text-xl text-gray-100 max-w-3xl mx-auto font-medium">
              Get started in minutes with our simple three-step process
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                step: "01",
                title: "Describe Your Topic",
                description: "Simply tell us what you want to learn about - any subject, any complexity level",
                icon: "✍️"
              },
              {
                step: "02",
                title: "AI Generates Content",
                description: "Our advanced AI creates comprehensive study materials tailored to your needs",
                icon: "🤖"
              },
              {
                step: "03",
                title: "Start Learning",
                description: "Dive into interactive quizzes, flashcards, and study materials immediately",
                icon: "🚀"
              }
            ].map((step, index) => (
              <motion.div
                key={index}
                className="text-center"
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
              >
                <div className="w-20 h-20 bg-gradient-to-r from-blue-600 to-cyan-600 rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-6">
                  {step.icon}
                </div>
                <div className="text-sm font-semibold text-blue-300 mb-2">{step.step}</div>
                <h3 className="text-xl font-semibold mb-4 text-white">{step.title}</h3>
                <p className="text-gray-200 font-medium">{step.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8 text-center">
            {[
              { number: "50K+", label: "Active Students", icon: "👥" },
              { number: "100K+", label: "Courses Created", icon: "📚" },
              { number: "98%", label: "Success Rate", icon: "🎯" },
              { number: "24/7", label: "AI Support", icon: "🤖" }
            ].map((stat, index) => (
              <motion.div
                key={index}
                className="group"
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                whileHover={{ scale: 1.05 }}
              >
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">
                  {stat.icon}
                </div>
                <div className="text-3xl md:text-4xl font-bold text-blue-300 mb-2">{stat.number}</div>
                <div className="text-gray-200 font-medium">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20 bg-gradient-to-r from-blue-900/25 to-cyan-900/25">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              What Our <span className="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">Students</span> Say
            </h2>
            <p className="text-xl text-gray-100 max-w-3xl mx-auto font-medium">
              Join thousands of students who have transformed their learning experience
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <motion.div
                key={index}
                className="p-8 rounded-2xl bg-white/8 backdrop-blur-sm border border-white/15 hover:border-blue-500/50 transition-all duration-300"
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                whileHover={{ scale: 1.02, y: -5 }}
              >
                <div className="flex items-center mb-6">
                  <div className="text-3xl mr-4">{testimonial.avatar}</div>
                  <div>
                    <div className="font-semibold text-white">{testimonial.name}</div>
                    <div className="text-sm text-blue-300 font-medium">{testimonial.role}</div>
                  </div>
                </div>
                <p className="text-gray-200 leading-relaxed font-medium">"{testimonial.content}"</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="container mx-auto px-4 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
            className="max-w-4xl mx-auto"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-8">
              Ready to Transform Your <span className="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">Learning</span>?
            </h2>
            <p className="text-xl text-gray-100 mb-12 max-w-2xl mx-auto font-medium">
              Join thousands of students who are already experiencing the future of education with AI-powered learning
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Link 
                href="/dashboard"
                className="px-8 py-4 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 rounded-xl font-semibold text-lg transition-all duration-200 transform hover:scale-105 shadow-lg hover:shadow-blue-500/25"
              >
                Start Learning Free
              </Link>
              <Link 
                href="/sign-up"
                className="px-8 py-4 border-2 border-blue-600 hover:bg-blue-600/20 rounded-xl font-semibold text-lg transition-all duration-200 transform hover:scale-105"
              >
                Create Account
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-white/15">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-blue-700 rounded-lg flex items-center justify-center">
                <svg fill="none" height="16" viewBox="0 0 40 48" width="14" xmlns="http://www.w3.org/2000/svg">
                  <g fill="white">
                    <path d="m32 26c0 5.5228-4.4772 10-10 10s-10-4.4772-10-10h-8c0 9.9411 8.0589 18 18 18s18-8.0589 18-18-8.0589-18-18-18v8c5.5228 0 10 4.4772 10 10z"/>
                    <path d="m10 4c0 5.52285-4.47715 10-10 10v8c9.94113 0 18-8.0589 18-18z" opacity=".5"/>
                  </g>
                </svg>
              </div>
              <span className="text-lg font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
                Easy Study
              </span>
            </div>
            <div className="text-gray-200 text-sm font-medium">
              © 2024 Easy Study. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}